version: '3'

services:
  server:
    container_name: server
    build: server
    ports:
      - "5000:5000"
    networks:
      - timer

  timer:
    container_name: timer
    build: timer
    networks:
      - timer

networks:
  timer:
