version: '3'

services:
  server:
    container_name: server
    build: server
    ports:
      - "5000:5000"

  timer:
    container_name: timer
    build: timer

  timer-ui:
    container_name: timer-ui
    build: timer-ui
    ports:
      - "8080:80"
